// Prediction explanation service to provide insights into how predictions are made
export interface PredictionFactor {
  name: string;
  weight: number; // -1 to 1, negative means disadvantage
  impact: 'high' | 'medium' | 'low';
  description: string;
}

export interface PredictionExplanation {
  modelName: string;
  outcome: string;
  confidence: number;
  keyFactors: PredictionFactor[];
  reasoning: string;
  strengths: string[];
  weaknesses: string[];
  recommendations: string[];
}

// Mock prediction explanations for different models and outcomes
// In a real application, this would be generated by the ML models
export const generatePredictionExplanation = (
  modelName: string,
  outcome: string,
  confidence: number,
  homeTeamStats: { goals: number; shots: number; shotsOnTarget: number; redCards: number },
  awayTeamStats: { goals: number; shots: number; shotsOnTarget: number; redCards: number }
): PredictionExplanation => {
  // Analyze team stats to generate factors
  const factors: PredictionFactor[] = [];
  
  // Goal difference factor
  const goalDifference = homeTeamStats.goals - awayTeamStats.goals;
  factors.push({
    name: "Goal Difference",
    weight: Math.min(1, Math.max(-1, goalDifference / 10)),
    impact: Math.abs(goalDifference) > 5 ? 'high' : Math.abs(goalDifference) > 2 ? 'medium' : 'low',
    description: `Home team has scored ${homeTeamStats.goals} goals, away team has scored ${awayTeamStats.goals}`
  });
  
  // Shot efficiency factor
  const homeShotEfficiency = homeTeamStats.shots > 0 ? homeTeamStats.shotsOnTarget / homeTeamStats.shots : 0;
  const awayShotEfficiency = awayTeamStats.shots > 0 ? awayTeamStats.shotsOnTarget / awayTeamStats.shots : 0;
  const shotEfficiencyDiff = homeShotEfficiency - awayShotEfficiency;
  factors.push({
    name: "Shot Efficiency",
    weight: Math.min(1, Math.max(-1, shotEfficiencyDiff * 5)),
    impact: Math.abs(shotEfficiencyDiff) > 0.2 ? 'high' : Math.abs(shotEfficiencyDiff) > 0.1 ? 'medium' : 'low',
    description: `Home team shot efficiency: ${(homeShotEfficiency * 100).toFixed(1)}%, away team: ${(awayShotEfficiency * 100).toFixed(1)}%`
  });
  
  // Discipline factor (red cards)
  const disciplineDiff = awayTeamStats.redCards - homeTeamStats.redCards;
  factors.push({
    name: "Discipline",
    weight: Math.min(1, Math.max(-1, disciplineDiff * 0.5)),
    impact: Math.abs(disciplineDiff) > 1 ? 'high' : disciplineDiff > 0 ? 'medium' : 'low',
    description: `Home team red cards: ${homeTeamStats.redCards}, away team red cards: ${awayTeamStats.redCards}`
  });
  
  // Sort factors by impact
  factors.sort((a, b) => {
    const impactOrder = { high: 3, medium: 2, low: 1 };
    return impactOrder[b.impact] - impactOrder[a.impact];
  });
  
  // Generate reasoning based on factors
  let reasoning = "";
  if (outcome === "Home Win") {
    reasoning = `The model predicts a home win based on ${factors[0].name} being the strongest factor. `;
    reasoning += `The home team's ${factors[0].description.toLowerCase()} gives them a significant advantage.`;
  } else if (outcome === "Away Win") {
    reasoning = `The model predicts an away win primarily due to ${factors[0].name}. `;
    reasoning += `The away team's ${factors[0].description.toLowerCase()} provides a clear edge.`;
  } else {
    reasoning = `The model predicts a draw as the most likely outcome. `;
    reasoning += `While ${factors[0].name} favors the home team, ${factors[1]?.name?.toLowerCase() || 'other factors'} balance this out.`;
  }
  
  // Generate strengths
  const strengths: string[] = [];
  factors.filter(f => f.weight > 0.3).forEach(factor => {
    strengths.push(`${factor.name}: Strong positive impact`);
  });
  
  if (strengths.length === 0) {
    strengths.push("Balanced team statistics");
  }
  
  // Generate weaknesses
  const weaknesses: string[] = [];
  factors.filter(f => f.weight < -0.3).forEach(factor => {
    weaknesses.push(`${factor.name}: Significant disadvantage`);
  });
  
  if (weaknesses.length === 0) {
    weaknesses.push("No major statistical disadvantages");
  }
  
  // Generate recommendations
  const recommendations: string[] = [];
  if (homeTeamStats.redCards > 1) {
    recommendations.push("Home team should focus on discipline to avoid red cards");
  }
  if (awayTeamStats.redCards > 1) {
    recommendations.push("Away team needs to maintain composure to avoid dismissals");
  }
  if (homeShotEfficiency < 0.3) {
    recommendations.push("Home team should work on shot accuracy in training");
  }
  if (awayShotEfficiency < 0.3) {
    recommendations.push("Away team should improve finishing in training");
  }
  
  if (recommendations.length === 0) {
    recommendations.push("Both teams are well-balanced - focus on execution");
  }
  
  return {
    modelName,
    outcome,
    confidence,
    keyFactors: factors,
    reasoning,
    strengths,
    weaknesses,
    recommendations
  };
};

// Function to get factor impact color
export const getFactorImpactColor = (impact: string): string => {
  switch (impact) {
    case 'high':
      return 'text-red-600 dark:text-red-400';
    case 'medium':
      return 'text-yellow-600 dark:text-yellow-400';
    case 'low':
      return 'text-green-600 dark:text-green-400';
    default:
      return 'text-gray-600 dark:text-gray-400';
  }
};

// Function to get factor weight color
export const getFactorWeightColor = (weight: number): string => {
  if (weight > 0.5) return 'text-green-600 dark:text-green-400';
  if (weight > 0.2) return 'text-green-500 dark:text-green-300';
  if (weight > -0.2) return 'text-gray-500 dark:text-gray-400';
  if (weight > -0.5) return 'text-orange-500 dark:text-orange-300';
  return 'text-red-600 dark:text-red-400';
};